server:
  port: 8030
spring:
  application:
    name: getway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    provider: /p/**     # 给服务名称为provider的服务设置映射  /p/ ==> 协议://ip:端口号